name: run test cases

on: 
  discussion_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]

jobs:
  run-test-cases:
    if: |
      contains(github.event.comment.body, '@cocos-robot run test cases')

    runs-on: run-test-win01

    steps:
      - name: 'Checkout engine'
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          path: engine

      - name: 'CocosCreator version'
        shell: bash
        run: |
          echo "CocosCreator Version: ${{github.event.pull_request.head.ref}}

      - name: 'npm install'
        run: |
          cd engine
          npm -v
          npm install --registry https://registry.npm.taobao.org

      - name: 'Call run test cases job'
        run: |
          python3 -u ./pr-test/main.py ${{github.base_ref}}
